version: '2.4'
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432
    logging:
      driver: "none"
  sync:
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./attendance_id:/attendance_id
      - ./db_init:/db_init
      - ./src:/src
    stdin_open: true
    tty: true
